//! A hash reads its message 64 bytes at a time and carries eight words of
//! state, so what it holds should be a property of the algorithm rather than
//! of the message. Until kanso#1580 `sha256/hex` held every block it had read,
//! and the peak grew with the message. It holds only its padded copy of the
//! message now, and the spec pins that.
//!
//! This asserts what the hash DOES, not what it should do. The numbers are
//! deterministic to the byte, so they are pinned rather than bounded, and a
//! change to what the hash holds turns this red. That is the point: the entry
//! that stops matching is the reminder, the same contract
//! tests/golden/wasm_gaps.txt keeps.
//!
//! The next three paragraphs describe the hash as it was before kanso#1580,
//! and are kept because the figures in them were measured then.
//!
//! WHY IT MATTERS AWAY FROM THE TEST. `scripts/fingerprint` digests the site's
//! assets, and docs/kanso.wasm is 1,604,098 bytes. At this rate that is roughly
//! eleven gigabytes of live arena for one file; measured, the kernel's own
//! out-of-memory report for that run read anon-rss 13,954,684 kB. The
//! asset-digests job passes on CI, so the runner has headroom this container
//! did not — but the headroom shrinks by about seven kilobytes for every byte
//! added to the blob, and nothing in the tree was watching that.
//!
//! The in-place append is NOT the cause and was the first guess: at 25,000
//! bytes the run reads push_mut_fast=1,904,531 against push_mut_slow=125,541,
//! so 93.8% of appends already take the fast path. What the counters do say is
//! that nothing is ever reclaimed — cohort_frees=0, and alloc_bytes lands
//! within half a per cent of arena_peak_bytes, which is one fact said twice:
//! every byte allocated is still live when the program ends. 89% of that peak
//! is buffer (sh_buf=220,980,512 of 247,463,936).

use std::process::Command;

/// Peak arena bytes for hashing `n` generated bytes.
fn peak_bytes(n: u64) -> u64 {
    let dir = std::env::temp_dir().join(format!("kanso-sha256-peak-{n}"));
    std::fs::create_dir_all(&dir).expect("a directory to run in");
    // The message is built rather than read so the spec needs no fixture, and
    // `% 251` keeps it from being a run of one repeated byte.
    let program = format!(
        "import \"std/sha256\"\n\n\
         fn bytes 0 acc\n  acc\n\n\
         fn bytes n acc\n  bytes (n - 1) (push acc (n % 251))\n\n\
         print (sha256/hex (bytes {n} []))\n"
    );
    std::fs::write(dir.join("run.kso"), program).expect("the program writes");

    let done = Command::new(env!("CARGO_BIN_EXE_kanso"))
        .arg("play")
        .arg("run.kso")
        .env("KANSO_COUNTERS", "1")
        .current_dir(&dir)
        .output()
        .expect("kanso runs");
    let said = String::from_utf8_lossy(&done.stderr).into_owned();
    let _ = std::fs::remove_dir_all(&dir);

    said.lines()
        .find_map(|l| l.trim().strip_prefix("arena_peak_bytes=")?.parse().ok())
        .unwrap_or_else(|| panic!("no arena_peak_bytes in:\n{said}"))
}

/// The hash streams its blocks now, and the peak left is the padded message.
///
/// The history of the pins, so it is not re-derived. Until 2026-09-07 they
/// were 7,340,032 at 1,024 bytes and 14,680,064 at 2,048, exactly linear: the
/// round table was rebuilt at every `rounds[at]`. Until 2026-09-15 they were
/// 17,825,808 and 40,894,496 at 65,536 and 131,072 bytes, and until
/// 2026-09-23 19,922,976 and 32,505,888, re-pinned when the empty list
/// literal opened with room for four. Each of those grew with the message,
/// and the block loop carried its eight words as a list.
///
/// kanso#1580 carries the eight words as eight scalar arguments, the loop
/// rewinds after every block, and the two old sizes read the same number:
/// the reading this spec's earlier note said a streaming hash would give.
/// The third size is what still grows. `padded_bytes` copies the message to
/// append the terminator and the length, and a copy of `padded_bytes` made
/// public and called alone, with no compression at all, reads 7,340,064,
/// 7,340,064 and 24,117,296 at these three sizes: the same three numbers as
/// the whole hash, byte for byte. So everything the hash holds past the
/// arena's floor is that copy, and a padding that feeds the last block from
/// the message rather than copying it would move the third pin.
#[test]
fn a_hash_holds_its_padded_message_and_nothing_per_block() {
    let short = peak_bytes(65_536);
    let long = peak_bytes(131_072);
    let longer = peak_bytes(262_144);

    assert_eq!(short, 7_340_064, "the 65,536-byte peak moved");
    assert_eq!(long, 7_340_064, "the 131,072-byte peak moved");
    assert_eq!(longer, 24_117_296, "the 262,144-byte peak moved");
}
