//! A hash reads its message 64 bytes at a time and carries eight words of
//! state, so what it holds is a property of the algorithm rather than of the
//! message. This asserts that: three sizes, one number.
//!
//! It did not hold until 2026-08-31, and the version of this file that ran
//! before then pinned the failure — `a_hash_holds_every_block_it_has_read`,
//! 7,340,032 bytes at 1,024 and 14,680,064 at 2,048, with a note saying that
//! when the hash learned to stream, the assertion was the thing to delete.
//! This is that deletion. What changed is in `beat.rs`: the analysis decided
//! which loops could rewind their arena by reading the declaration's source
//! path, and every `std/` module lost the rewind, so the digest never gave a
//! block back.
//!
//! WHY IT MATTERS AWAY FROM THE TEST. `scripts/fingerprint` digests the site's
//! assets, and docs/kanso.wasm is 1,604,098 bytes. At the old rate — about
//! seven kilobytes of live arena for every byte hashed — that was roughly
//! eleven gigabytes; measured, the kernel's own out-of-memory report for that
//! run read anon-rss 13,954,684 kB.
//!
//! WHAT IS AND IS NOT CLAIMED ABOVE THESE SIZES. The old peak was linear and
//! exact — about ten thousand bytes of arena for every byte hashed, at every
//! size. The new one still grows, and how it grows is not characterised.
//! Natively, from a file: one 1 MiB block from 1 KB through 32 KB, 4,194,320
//! bytes at 64 KB and at 100 KB, 12,582,944 at 200 KB, 13,631,520 at 400 KB —
//! 1,048 bytes per input byte at the small end and 34 at the large.
//!
//! What is left is `sha256/padded_bytes`, which opens with `list/to_list b`
//! and so holds the message as a list of integers, sixteen arena bytes an
//! input byte, for as long as the walk indexes it. The steps are that list's
//! buffer doubling past a power of two. It is the library's to fix and this
//! spec does not pin it: the sizes below are small enough that the walk, not
//! the message, is what they measure. The wasm blob was not re-measured — a
//! 100 KB digest takes about forty seconds in this container.
//!
//! The peak is pinned exactly rather than as a ratio. A ratio stays green if
//! both numbers grow together, which is the shape this spec exists to catch,
//! and the arena's first block is 1 MiB so a digest that holds one reads it to
//! the byte.

use std::process::Command;

/// Peak arena bytes for hashing `n` generated bytes.
fn peak_bytes(n: u64) -> u64 {
    let dir = std::env::temp_dir().join(format!("kanso-sha256-peak-{n}"));
    std::fs::create_dir_all(&dir).expect("a directory to run in");
    // The message is built rather than read so the spec needs no fixture, and
    // `% 251` keeps it from being a run of one repeated byte.
    let program = format!(
        "import \"std/sha256\"\n\n\
         fn bytes 0 acc\n  acc\n\n\
         fn bytes n acc\n  bytes (n - 1) (push acc (n % 251))\n\n\
         print (sha256/hex (bytes {n} []))\n"
    );
    std::fs::write(dir.join("run.kso"), program).expect("the program writes");

    let done = Command::new(env!("CARGO_BIN_EXE_kanso"))
        .arg("play")
        .arg("run.kso")
        .env("KANSO_COUNTERS", "1")
        .current_dir(&dir)
        .output()
        .expect("kanso runs");
    let said = String::from_utf8_lossy(&done.stderr).into_owned();
    let _ = std::fs::remove_dir_all(&dir);

    said.lines()
        .find_map(|l| l.trim().strip_prefix("arena_peak_bytes=")?.parse().ok())
        .unwrap_or_else(|| panic!("no arena_peak_bytes in:\n{said}"))
}

/// Four times the message, the same arena. The three sizes are read rather
/// than the two a slope needs, because two points fit any line and the third
/// is what says the number is a constant.
#[test]
fn a_hash_holds_one_block_however_long_the_message() {
    let short = peak_bytes(1024);
    let mid = peak_bytes(2048);
    let long = peak_bytes(4096);

    assert_eq!(short, 1_048_576, "the 1,024-byte peak moved");
    assert_eq!(mid, 1_048_576, "the 2,048-byte peak moved");
    assert_eq!(long, 1_048_576, "the 4,096-byte peak moved");
}
