//! A hash reads its message 64 bytes at a time and carries eight words of
//! state, so what it holds should be a property of the algorithm rather than
//! of the message. `sha256/hex` holds the message instead: doubling the input
//! doubles the peak arena, exactly, and the constant is about seven thousand
//! bytes of live memory for every byte hashed.
//!
//! This asserts what the hash DOES, not what it should do. The numbers are
//! deterministic to the byte — three runs of each size agree — so they are
//! pinned rather than bounded, and a change that makes the hash stream will
//! turn this red. That is the point: the entry that stops matching is the
//! reminder, the same contract tests/golden/wasm_gaps.txt keeps.
//!
//! WHY IT MATTERS AWAY FROM THE TEST. `scripts/fingerprint` digests the site's
//! assets, and docs/kanso.wasm is 1,604,098 bytes. At this rate that is roughly
//! eleven gigabytes of live arena for one file; measured, the kernel's own
//! out-of-memory report for that run read anon-rss 13,954,684 kB. The
//! asset-digests job passes on CI, so the runner has headroom this container
//! did not — but the headroom shrinks by about seven kilobytes for every byte
//! added to the blob, and nothing in the tree was watching that.
//!
//! The in-place append is NOT the cause and was the first guess: at 25,000
//! bytes the run reads push_mut_fast=1,904,531 against push_mut_slow=125,541,
//! so 93.8% of appends already take the fast path. What the counters do say is
//! that nothing is ever reclaimed — cohort_frees=0, and alloc_bytes lands
//! within half a per cent of arena_peak_bytes, which is one fact said twice:
//! every byte allocated is still live when the program ends. 89% of that peak
//! is buffer (sh_buf=220,980,512 of 247,463,936).

use std::process::Command;

/// Peak arena bytes for hashing `n` generated bytes.
fn peak_bytes(n: u64) -> u64 {
    let dir = std::env::temp_dir().join(format!("kanso-sha256-peak-{n}"));
    std::fs::create_dir_all(&dir).expect("a directory to run in");
    // The message is built rather than read so the spec needs no fixture, and
    // `% 251` keeps it from being a run of one repeated byte.
    let program = format!(
        "import \"std/sha256\"\n\n\
         fn bytes 0 acc\n  acc\n\n\
         fn bytes n acc\n  bytes (n - 1) (push acc (n % 251))\n\n\
         print (sha256/hex (bytes {n} []))\n"
    );
    std::fs::write(dir.join("run.kso"), program).expect("the program writes");

    let done = Command::new(env!("CARGO_BIN_EXE_kanso"))
        .arg("play")
        .arg("run.kso")
        .env("KANSO_COUNTERS", "1")
        .current_dir(&dir)
        .output()
        .expect("kanso runs");
    let said = String::from_utf8_lossy(&done.stderr).into_owned();
    let _ = std::fs::remove_dir_all(&dir);

    said.lines()
        .find_map(|l| l.trim().strip_prefix("arena_peak_bytes=")?.parse().ok())
        .unwrap_or_else(|| panic!("no arena_peak_bytes in:\n{said}"))
}

/// Twice the message, more than twice the arena. A streaming hash would
/// read the same number twice here, and when one does this assertion is the
/// thing to delete.
///
/// Until 2026-09-07 the pins were 7,340,032 at 1,024 bytes and 14,680,064 at
/// 2,048, exactly linear, and seven kilobytes of arena a message byte. That
/// was the round table: sha256's sixty-four constants were joined from eleven
/// literal lists at every `rounds[at]`, sixty-four times a block, and the
/// garbage of rebuilding them was the peak. Every constant is built once now,
/// and what is left is the hash's own retention -- the schedule and the
/// working words of every block, still held to the end -- which reads
/// 1,048,576 at both old sizes because that is one arena block, the floor
/// nothing smaller can show. The sizes below sit above the floor. The peak
/// is no longer an exact doubling because the arena grows by whole blocks,
/// but it grows with the message, which is the defect this spec is about.
#[test]
fn a_hash_holds_every_block_it_has_read() {
    let short = peak_bytes(65_536);
    let long = peak_bytes(131_072);

    assert_eq!(short, 17_825_808, "the 65,536-byte peak moved");
    assert_eq!(long, 40_894_496, "the 131,072-byte peak moved");
    assert!(
        long > short,
        "the peak stopped growing with the message: {short} at 65,536 bytes \
         and {long} at 131,072"
    );
}
