"""Write commonmark/entities.kso from Python's copy of the HTML5 entity list.

CommonMark recognises an entity only with its closing semicolon, so the
legacy names that HTML also accepts without one are left out.
"""
import html.entities
import os

ESCAPES = {'"': '\\"', '\\': '\\\\', '{': '\\{', '\n': '\\n', '\t': '\\t'}


def literal(s):
    return '"' + ''.join(ESCAPES.get(ch, ch) for ch in s) + '"'


def main():
    names = sorted((k[:-1], v) for k, v in html.entities.html5.items()
                   if k.endswith(';'))
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, '..', 'commonmark', 'entities.kso')
    with open(out, 'w') as f:
        f.write('# The HTML5 named character references, generated by\n')
        f.write('# tools/gen_entities.py. A map literal cannot span lines,\n')
        f.write('# so the table is built as a chain of puts.\n')
        f.write('entity_table = {}\n')
        for name, value in names:
            f.write('  . put %s %s\n' % (literal(name), literal(value)))


main()
