// Code generated by "stringer -type=AssignType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL_ASSIGN-0]
	_ = x[ASSIGN-1]
	_ = x[PLUS_ASSIGN-2]
	_ = x[MINUS_ASSIGN-3]
	_ = x[STAR_ASSIGN-4]
	_ = x[SLASH_ASSIGN-5]
	_ = x[PERCENT_ASSIGN-6]
}

const _AssignType_name = "ILLEGAL_ASSIGNASSIGNPLUS_ASSIGNMINUS_ASSIGNSTAR_ASSIGNSLASH_ASSIGNPERCENT_ASSIGN"

var _AssignType_index = [...]uint8{0, 14, 20, 31, 43, 54, 66, 80}

func (i AssignType) String() string {
	if i < 0 || i >= AssignType(len(_AssignType_index)-1) {
		return "AssignType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssignType_name[_AssignType_index[i]:_AssignType_index[i+1]]
}
