// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENTIFIER-2]
	_ = x[NUMBER-3]
	_ = x[HEX_NUMBER-4]
	_ = x[STRING-5]
	_ = x[FUN-6]
	_ = x[LET-7]
	_ = x[IF-8]
	_ = x[ELSE-9]
	_ = x[RETURN-10]
	_ = x[MODULE-11]
	_ = x[ASSERT-12]
	_ = x[USE-13]
	_ = x[STRUCT-14]
	_ = x[WRITES-15]
	_ = x[READS-16]
	_ = x[PUBLIC-17]
	_ = x[MUT-18]
	_ = x[PLUS-19]
	_ = x[INCREMENT-20]
	_ = x[MINUS-21]
	_ = x[DECREMENT-22]
	_ = x[STAR-23]
	_ = x[STAR_STAR-24]
	_ = x[SLASH-25]
	_ = x[BANG-26]
	_ = x[BANG_EQUAL-27]
	_ = x[EQUAL-28]
	_ = x[EQUAL_EQUAL-29]
	_ = x[LESS-30]
	_ = x[LESS_EQUAL-31]
	_ = x[GREATER-32]
	_ = x[GREATER_EQUAL-33]
	_ = x[AND-34]
	_ = x[AMPERSAND-35]
	_ = x[OR-36]
	_ = x[PIPE-37]
	_ = x[PLUS_EQUAL-38]
	_ = x[MINUS_EQUAL-39]
	_ = x[STAR_EQUAL-40]
	_ = x[SLASH_EQUAL-41]
	_ = x[PERCENT_EQUAL-42]
	_ = x[COMMA-43]
	_ = x[DOT-44]
	_ = x[SEMICOLON-45]
	_ = x[COLON-46]
	_ = x[DOUBLE_COLON-47]
	_ = x[LEFT_PAREN-48]
	_ = x[RIGHT_PAREN-49]
	_ = x[LEFT_BRACE-50]
	_ = x[RIGHT_BRACE-51]
	_ = x[LEFT_BRACKET-52]
	_ = x[RIGHT_BRACKET-53]
	_ = x[POUND-54]
	_ = x[COMMENT-55]
	_ = x[DOC_COMMENT-56]
	_ = x[BLOCK_COMMENT-57]
}

const _TokenType_name = "ILLEGALEOFIDENTIFIERNUMBERHEX_NUMBERSTRINGFUNLETIFELSERETURNMODULEASSERTUSESTRUCTWRITESREADSPUBLICMUTPLUSINCREMENTMINUSDECREMENTSTARSTAR_STARSLASHBANGBANG_EQUALEQUALEQUAL_EQUALLESSLESS_EQUALGREATERGREATER_EQUALANDAMPERSANDORPIPEPLUS_EQUALMINUS_EQUALSTAR_EQUALSLASH_EQUALPERCENT_EQUALCOMMADOTSEMICOLONCOLONDOUBLE_COLONLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACELEFT_BRACKETRIGHT_BRACKETPOUNDCOMMENTDOC_COMMENTBLOCK_COMMENT"

var _TokenType_index = [...]uint16{0, 7, 10, 20, 26, 36, 42, 45, 48, 50, 54, 60, 66, 72, 75, 81, 87, 92, 98, 101, 105, 114, 119, 128, 132, 141, 146, 150, 160, 165, 176, 180, 190, 197, 210, 213, 222, 224, 228, 238, 249, 259, 270, 283, 288, 291, 300, 305, 317, 327, 338, 348, 359, 371, 384, 389, 396, 407, 420}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
