# a comment
x = 1 # trailing
y = a\#b
   # indented comment
all: # comment after colon
	@echo x=[$(x)] y=[$(y)]
# comment inside a recipe is make's
	@echo still the recipe # this one goes to the shell
